### ISSUE TITLE
build error on compile

### ISSUE THREAD

**Issue by mbsanchez** [yangliu28/minimal_robot_gripper#1]
I found a build error when compile the package, i found the solution here: https://github.com/ros/genmsg/issues/9, you can see the error on the next screen.

![build error](https://user-images.githubusercontent.com/143726/35150850-4bb1bd38-fd1c-11e7-83df-2315e832932f.png)

The issue is becase it try to build the cpp source code before generate the service and action headers, to fix the error we need to add the next code to the CMakeList.txt in order that the compiler can build  generate the header before build the cpp files.

`target_link_libraries(gripper_robot_controller ${catkin_LIBRARIES})
target_link_libraries(gripper_robot_kpkv_serviceClient ${catkin_LIBRARIES})
target_link_libraries(gripper_robot_trajectory_action_server ${catkin_LIBRARIES})
target_link_libraries(gripper_robot_trajectory_action_client ${catkin_LIBRARIES})`

I'm going to fork your repo and make a pull request.

**Comment by yangliu28** [comment]
I've known this issue, and used to work around it by compiling specific headers.
I haven't played with ROS for a while, and assume you find the right solution and will merge the pull request. Thanks @mbsanchez.

**Comment by mbsanchez** [comment]
You'are welcome. It build well now, i've tested many times.

Manuel B. Sanchez

On janv. 19 2018, at 9:45 pm, Yang Liu <notifications@github.com> wrote:

I've known this issue, and used to work around it by compiling specific headers.
I haven't played with ROS for a while, and assume you find the right solution and will merge the pull request. Thanks @mbsanchez<https://github.com/mbsanchez?recipient=mention%40noreply.github.com>.

**Comment by mbsanchez** [comment]
You'are welcome. It build well now, i've tested many times.

Manuel B. Sanchez

On janv. 19 2018, at 9:45 pm, Yang Liu <notifications@github.com> wrote:

I've known this issue, and used to work around it by compiling specific headers.
I haven't played with ROS for a while, and assume you find the right solution and will merge the pull request. Thanks @mbsanchez<https://github.com/mbsanchez?recipient=minimal_robot_gripper%40noreply.github.com>.

**Comment by mbsanchez** [comment]
You'are welcome. It build well now, i've tested many times.

Manuel B. Sanchez

On janv. 19 2018, at 9:45 pm, Yang Liu <notifications@github.com> wrote:

I've known this issue, and used to work around it by compiling specific headers.
I haven't played with ROS for a while, and assume you find the right solution and will merge the pull request. Thanks @mbsanchez<https://github.com/mbsanchez?recipient=reply%2B0002316ea37c33104bfd6b58e3ac9c41cf250646006b696392cf00000001167a1b0192a169ce11487329%40reply.github.com>.
