### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by tinjiang1012** [yangliu28/minimal_robot_gripper#3]
hello there~
I tried to compile the package, however it came out the error messages as below. I am a beginner to the ROS, thus I quite not understand the meaning of those messages.  Can anybody give me a hand?

error message:
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  ps5_yxl1450/CMakeLists.txt:7 (find_package)

-- Could not find the required component 'catkin_simple'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  ps5_yxl1450/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/panlab/test_arm/build/CMakeFiles/CMakeOutput.log".
See also "/home/panlab/test_arm/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by yangliu28** [comment]
Looks like you don't have `catkin_simple` installed. You could either install `ros-indigo-catkin-simple`, or convert the *CMakeLists.txt* to the standard catkin format.

For the first, try `sudo apt-get install ros-indigo-catkin-simple`, not sure it would work.

For the second, please refer to [http://wiki.ros.org/catkin/CMakeLists.txt](http://wiki.ros.org/catkin/CMakeLists.txt)

**Comment by yangliu28** [comment]
@tinjiang1012 I assume you already figure it out since there is no further comment. Reopen if necessary.
